# Generated by Django 3.1.7 on 2022-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220212_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
